-- MySQL Script generated by MySQL Workbench
-- Sun Mar  6 00:25:18 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema landfill-data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema landfill-data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `landfill-data` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `landfill-data` ;

-- -----------------------------------------------------
-- Table `landfill-data`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landfill-data`.`Employee` ;

CREATE TABLE IF NOT EXISTS `landfill-data`.`Employee` (
  `EmployeePK` INT NOT NULL COMMENT '',
  `Lastname` VARCHAR(45) NULL COMMENT '',
  `Firstname` VARCHAR(45) NULL COMMENT '',
  `Role` VARCHAR(45) NULL COMMENT '',
  `CityId` VARCHAR(10) NULL COMMENT '',
  `EmailAdd` VARCHAR(45) NULL COMMENT '',
  `Initials` VARCHAR(6) NULL COMMENT '',
  PRIMARY KEY (`EmployeePK`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landfill-data`.`Instrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landfill-data`.`Instrument` ;

CREATE TABLE IF NOT EXISTS `landfill-data`.`Instrument` (
  `InstrumentPK` INT NOT NULL COMMENT '',
  `ManufacturerSerialNumber` VARCHAR(45) NULL COMMENT '',
  `Model` VARCHAR(45) NULL COMMENT '',
  `Status` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`InstrumentPK`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landfill-data`.`Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landfill-data`.`Site` ;

CREATE TABLE IF NOT EXISTS `landfill-data`.`Site` (
  `SitePK` INT NOT NULL COMMENT '',
  `Name` VARCHAR(60) NULL COMMENT '',
  `SiteCode` VARCHAR(5) NULL COMMENT '',
  `ShortName` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`SitePK`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landfill-data`.`SamplingPoints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landfill-data`.`SamplingPoints` ;

CREATE TABLE IF NOT EXISTS `landfill-data`.`SamplingPoints` (
  `SamplingPointsPK` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `SitePK` INT NULL COMMENT '',
  `PointType` VARCHAR(15) NULL COMMENT '',
  `PointId` VARCHAR(15) NULL COMMENT '',
  `Status` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`SamplingPointsPK`)  COMMENT '',
  INDEX `SitePK_idx` (`SitePK` ASC)  COMMENT '',
  CONSTRAINT `SitePK`
    FOREIGN KEY (`SitePK`)
    REFERENCES `landfill-data`.`Site` (`SitePK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landfill-data`.`InstantaneousData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landfill-data`.`InstantaneousData` ;

CREATE TABLE IF NOT EXISTS `landfill-data`.`InstantaneousData` (
  `InstantaneousDataPK` INT NOT NULL COMMENT '',
  `SitePK` INT NULL COMMENT '',
  `EmployeePK` INT NULL COMMENT '',
  `StartTime` DATETIME NULL COMMENT '',
  `FinishTime` DATETIME NULL COMMENT '',
  `InstrumentPK` INT NULL COMMENT '',
  `maxCH` VARCHAR(45) NULL COMMENT '',
  `SamplingPointsPK` INT NULL COMMENT '',
  PRIMARY KEY (`InstantaneousDataPK`)  COMMENT '',
  INDEX `InspectorId_idx` (`EmployeePK` ASC)  COMMENT '',
  INDEX `InstrumentId_idx` (`InstrumentPK` ASC)  COMMENT '',
  INDEX `LandfillId_idx` (`SitePK` ASC)  COMMENT '',
  INDEX `SamplingPointsPK_idx` (`SamplingPointsPK` ASC)  COMMENT '',
  CONSTRAINT `EmployeePK`
    FOREIGN KEY (`EmployeePK`)
    REFERENCES `landfill-data`.`Employee` (`EmployeePK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InstrumentPK`
    FOREIGN KEY (`InstrumentPK`)
    REFERENCES `landfill-data`.`Instrument` (`InstrumentPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SitePK`
    FOREIGN KEY (`SitePK`)
    REFERENCES `landfill-data`.`Site` (`SitePK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SamplingPointsPK`
    FOREIGN KEY (`SamplingPointsPK`)
    REFERENCES `landfill-data`.`SamplingPoints` (`SamplingPointsPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landfill-data`.`IntegrateData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landfill-data`.`IntegrateData` ;

CREATE TABLE IF NOT EXISTS `landfill-data`.`IntegrateData` (
  `IntegrateSurveyId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IntegrateSurveyId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landfill-data`.`IME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landfill-data`.`IME` ;

CREATE TABLE IF NOT EXISTS `landfill-data`.`IME` (
  `IMEPK` INT NOT NULL COMMENT '',
  `ReadingDate` DATETIME NULL COMMENT '',
  `Description` VARCHAR(245) NULL COMMENT '',
  `EmployeePK` INT NULL COMMENT '',
  `Value` VARCHAR(45) NULL COMMENT '',
  `IMENumber` VARCHAR(9) NULL COMMENT '',
  PRIMARY KEY (`IMEPK`)  COMMENT '',
  INDEX `EmployeePK_idx` (`EmployeePK` ASC)  COMMENT '',
  CONSTRAINT `EmployeePK`
    FOREIGN KEY (`EmployeePK`)
    REFERENCES `landfill-data`.`Employee` (`EmployeePK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landfill-data`.`IMEPairing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `landfill-data`.`IMEPairing` ;

CREATE TABLE IF NOT EXISTS `landfill-data`.`IMEPairing` (
  `IMEPK` INT NOT NULL COMMENT '',
  `InstantaneousDataPK` INT NOT NULL COMMENT '',
  INDEX `InstantaneousDataPK_idx` (`InstantaneousDataPK` ASC)  COMMENT '',
  CONSTRAINT `InstantaneousDataPK`
    FOREIGN KEY (`InstantaneousDataPK`)
    REFERENCES `landfill-data`.`InstantaneousData` (`InstantaneousDataPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IMEPK`
    FOREIGN KEY (`IMEPK`)
    REFERENCES `landfill-data`.`IME` (`IMEPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
