-- MySQL Script generated by MySQL Workbench
-- Sun Mar  6 00:25:18 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeePK` INT NOT NULL COMMENT '',
  `Lastname` VARCHAR(45) NULL COMMENT '',
  `Firstname` VARCHAR(45) NULL COMMENT '',
  `Role` VARCHAR(45) NULL COMMENT '',
  `CityId` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`EmployeePK`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instrument` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instrument` (
  `InstrumentPK` INT NOT NULL COMMENT '',
  `ManufacturerSerialNumber` VARCHAR(45) NULL COMMENT '',
  `Model` VARCHAR(45) NULL COMMENT '',
  `Status` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`InstrumentPK`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Site` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Site` (
  `SitePK` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `GridCount` VARCHAR(45) NULL COMMENT '',
  `SiteCode` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`SitePK`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SiteSamplingPoint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SiteSamplingPoint` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SiteSamplingPoint` (
  `SiteSamplingPointPK` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `SitePK` INT NULL COMMENT '',
  `PointType` VARCHAR(10) NULL COMMENT '',
  `PointId` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`SiteSamplingPointPK`)  COMMENT '',
  INDEX `SitePK_idx` (`SitePK` ASC)  COMMENT '',
  CONSTRAINT `SitePK`
    FOREIGN KEY (`SitePK`)
    REFERENCES `mydb`.`Site` (`SitePK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InstantaneousData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InstantaneousData` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InstantaneousData` (
  `InstantaneousDataPK` INT NOT NULL COMMENT '',
  `SitePK` INT NULL COMMENT '',
  `EmployeePK` INT NULL COMMENT '',
  `StartTime` DATETIME NULL COMMENT '',
  `FinishTime` DATETIME NULL COMMENT '',
  `InstrumentPK` INT NULL COMMENT '',
  `maxCH` VARCHAR(45) NULL COMMENT '',
  `SiteSamplingPointPK` INT NULL COMMENT '',
  PRIMARY KEY (`InstantaneousDataPK`)  COMMENT '',
  INDEX `InspectorId_idx` (`EmployeePK` ASC)  COMMENT '',
  INDEX `InstrumentId_idx` (`InstrumentPK` ASC)  COMMENT '',
  INDEX `LandfillId_idx` (`SitePK` ASC)  COMMENT '',
  INDEX `SiteSamplingPointPK_idx` (`SiteSamplingPointPK` ASC)  COMMENT '',
  CONSTRAINT `EmployeePK`
    FOREIGN KEY (`EmployeePK`)
    REFERENCES `mydb`.`Employee` (`EmployeePK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InstrumentPK`
    FOREIGN KEY (`InstrumentPK`)
    REFERENCES `mydb`.`Instrument` (`InstrumentPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SitePK`
    FOREIGN KEY (`SitePK`)
    REFERENCES `mydb`.`Site` (`SitePK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SiteSamplingPointPK`
    FOREIGN KEY (`SiteSamplingPointPK`)
    REFERENCES `mydb`.`SiteSamplingPoint` (`SiteSamplingPointPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IntegrateData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IntegrateData` ;

CREATE TABLE IF NOT EXISTS `mydb`.`IntegrateData` (
  `IntegrateSurveyId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IntegrateSurveyId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IME` ;

CREATE TABLE IF NOT EXISTS `mydb`.`IME` (
  `IMEPK` INT NOT NULL COMMENT '',
  `CreateDate` DATETIME NULL COMMENT '',
  `Description` VARCHAR(245) NULL COMMENT '',
  `EmployeePK` INT NULL COMMENT '',
  `Value` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`IMEPK`)  COMMENT '',
  INDEX `EmployeePK_idx` (`EmployeePK` ASC)  COMMENT '',
  CONSTRAINT `EmployeePK`
    FOREIGN KEY (`EmployeePK`)
    REFERENCES `mydb`.`Employee` (`EmployeePK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IMEInstantaneousPair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IMEInstantaneousPair` ;

CREATE TABLE IF NOT EXISTS `mydb`.`IMEInstantaneousPair` (
  `IMEPK` INT NOT NULL COMMENT '',
  `InstantaneousDataPK` INT NOT NULL COMMENT '',
  INDEX `InstantaneousDataPK_idx` (`InstantaneousDataPK` ASC)  COMMENT '',
  CONSTRAINT `InstantaneousDataPK`
    FOREIGN KEY (`InstantaneousDataPK`)
    REFERENCES `mydb`.`InstantaneousData` (`InstantaneousDataPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IMEPK`
    FOREIGN KEY (`IMEPK`)
    REFERENCES `mydb`.`IME` (`IMEPK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
